### ISSUE TITLE
room610-table-object foot seems to be odd.

### ISSUE THREAD

**Issue by aginika** [euslisp/EusLisp#126]
long side and short side's direction is odd 
In Picture, left side leg is right.
![610-table](https://cloud.githubusercontent.com/assets/3803922/9171924/7fbe154a-3faa-11e5-9e39-20805d3bf2fb.png)

**Comment by k-okada** [comment]
Ok, please fix that. 1 st, please fix on euslib and convert to irteus


2015年8月10日月曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> long side and short side's direction is odd
> In Picture, left side leg is right.
> [image: 610-table]
> <https://cloud.githubusercontent.com/assets/3803922/9171924/7fbe154a-3faa-11e5-9e39-20805d3bf2fb.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/euslisp/EusLisp/issues/126>.
>


-- 
--
◉ Kei Okada

**Comment by aginika** [comment]
fixed
