### ISSUE TITLE
呼び出される関数の中で自身の関数の引数のリストが知りたい

### ISSUE THREAD

**Issue by furushchev** [euslisp/EusLisp#127]
このような関数or方法はあるのでしょうか？

例えば、

```lisp
(defun func1 (a1 &key k1 (k2 t))
  ... )
```

という関数があるとして、これを以下のようにcallした時に

```
(func1 "fuga")
```

関数内で

```lisp
(dolist (arg *args-of-this-func*)
  (format "~A: ~A~%" (car arg) (cdr arg))
;; => (:a1 . "fuga")
;;    (:k1 . nil)
;;    (:k2 . t)
```

のようにアクセスできると大変嬉しいです。

**Comment by garaemon** [comment]
`&rest args`ではだめですか?

**Comment by YoheiKakiuchi** [comment]
実際にどういう用途があるのかな？

**Comment by furushchev** [comment]
返信が遅れました。
関数の引数の値やシンボルなどをデータベースなどに入れたいと考えていました。
eus特有かもしれませんが`-`という変数にquoteされる形で入っているようです。

**Comment by snozawa** [comment]
> eus特有かもしれませんが-という変数にquoteされる形で入っているようです。

知らんかった！
