### ISSUE TITLE
リスト内のstringを検索して消したいです

### ISSUE THREAD

**Issue by kochigami** [euslisp/EusLisp#218]
これはできるけれど、
```
 delete 123 (list 123 345)
(345)
```

これはできません。
```
delete "123" (list "123" "345")
("123" "345")
```

どうすればいいでしょうか。ご迷惑をお掛けし申し訳ございません。

**Comment by kochigami** [comment]
普通に、文字が一致するリストの番号をみて、
新しいリストをつくる時に除いてできました。すみません。

**Comment by mmurooka** [comment]
`(delete "123" (list "123" "345") :test #'string=)`
でできます．

**Comment by kochigami** [comment]
ご返信が遅くなり大変申し訳ございません。

```:test```の意味は、
書かないと```eq```で評価をするが、```:test (またはtest-not) #' <function>``` とすることで他の関数でも評価できるようになるということなのですね。
ご教示ありがとうございました。
