### ISSUE TITLE
format関数のディレクティブに関する質問

### ISSUE THREAD

**Issue by M-Onitsuka** [euslisp/EusLisp#235]
euslisp(Common lisp)のformat関数のディレクティブにおいて，
```~a```と```~A```とではどういった違いがあるのでしょうか.

**Comment by k-okada** [comment]
違いはありません．ここだけでなく、Lispでは大文字と小文字の違いはありません．
```
1.eusgl$ (setq a 10)
10
2.eusgl$ (print A)
10
10
```
