### ISSUE TITLE
function "string-trim" behaves suspiciously

### ISSUE THREAD

**Issue by M-Onitsuka** [euslisp/EusLisp#249]
This  result is execution result when I used function "string-trim" on roseus, and I think this behavior differs from manual.
Is this correct behavior?
```
1.irteusgl$ setq str "test.dat"
"test.dat"
2.irteusgl$ string-trim ".dat" str
"es"
3.irteusgl$ string-trim ".dat" "state.dat"
"state"
4.irteusgl$ string-right-trim ".dat" str
"tes"
5.irteusgl$ string-right-trim ".dat" "state.dat"
"state"
```

**Comment by Affonso-Gui** [comment]
Do not worry, there is nothing wrong with euslisp here.

The function `string-trim` removes ANY of the characters present on the first parameter from both the start and the end of the second parameter string. It's more meant to be used like: 
```
(string-trim '(#\Space #\Tab #\Newline) " garbanzo beans
        ") =>  "garbanzo beans"
```
In the "test.dat" example it goes from the beginning like:
1st letter: `t` . Is present in ".dat" so delete it
2nd letter: `e` . Is not present in ".dat" so let it be
3rd letter: `s` . Is not present in ".dat" so let it be
4th letter: `t`: Is present in ".dat" so delete it
and so on, making it return `"es"` in the end. Same for `string-right-trim` and `string-left-trim`.

Please note that `(string-trim "ta.d" "test.dat")` also returns `"es"`.

If you just want to take the file extension you can for instance
```
(setq str "test.dat")
(subseq str 0 (position #\. str))
=> "test"
```
If it must be ".dat" I advice you to have a look at `search` function (not defined in euslisp though).

Some common lisp related links:
http://clhs.lisp.se/Body/f_stg_tr.htm
http://cl-cookbook.sourceforge.net/strings.html

**Comment by M-Onitsuka** [comment]
I got it. And thank you for your advice.
