### ISSUE TITLE
Mismatching of KEYWORKDPARAMETERLIMIT

### ISSUE THREAD

**Issue by snozawa** [euslisp/EusLisp#263]
I found mismatching of `KEYWORDPARAMETERLIMIT`.

`KEYWORDPARAMETERLIMIT` was extended from `32` to `128` in the following commit:
https://github.com/euslisp/EusLisp/commit/fb61d77e626318d55e6c40f1fb5b84cefd49fdbe

`comp.l` is still use `32` as the limit:
https://github.com/euslisp/EusLisp/blob/master/lisp/comp/comp.l#L1007-L1008

Therefore, functions or methods which have more than 32 key-word arguments cannot be compiled.
For example, write the following code to `test-keyword-parameter-compile-NG.l`
```
(defun test-keyword-parameter-compile-NG
  (&key
   key-01 key-02 key-03 key-04 key-05 key-06 key-07 key-08 key-09 key-10
   key-11 key-12 key-13 key-14 key-15 key-16 key-17 key-18 key-19 key-20
   key-21 key-22 key-23 key-24 key-25 key-26 key-27 key-28 key-29 key-30
   key-31 key-32
   )
  )
```
, and compile the file with the following command:
```
(comp:compile-file-if-src-newer "test-keyword-parameter-compile-NG.l" "/tmp/")
```

What is the recommended solution?
For example, add global variable for `KEYWORDPARAMETERLIMIT` and use it in `comp.l`?

Thanks.

**Comment by k-okada** [comment]
I think https://github.com/euslisp/EusLisp/pull/272 is ok
