### ISSUE TITLE
Segmentation Fault when launching roseus in 16.04

### ISSUE THREAD

**Issue by Affonso-Gui** [euslisp/EusLisp#291]
When using the latest versions for `jskeus` (https://github.com/euslisp/jskeus/commit/fa7b88fe5ba92b5e94d60a654bf4f9e14991b595) and `eus` (d7a32842361ecf10234895941e10f1620422ab7a) from source in Ubuntu 16.04, running `roseus` leads to:
```
roseus ;; Segmentation Fault.
;; in (load-library "roseus.so" '("roseus"))
;; You are still in a signal handler.
;;Try reset or throw to upper level as soon as possible.
;; code=1757534960 x=68c1d9c0 addr=5
```
This problem does not occur in Ubuntu 14.04 nor when using eus version https://github.com/euslisp/EusLisp/commit/1f5a9e92c7ac8663c606a892839fe1961c97971a.

Verified the above in a total of 5 PCs (three of them 16.04, two of them 14.04).
@weiqiyang
@itohdak

**Comment by YoheiKakiuchi** [comment]
roseus may be compiled with  (euslisp/jskeus@fa7b88f)
(I do not test yet)

**Comment by Affonso-Gui** [comment]
using roseus from apt seemed to be the reason for this. (conflicting definitions in eus.h)

Still testing, but seems that compiling that from source too does the job.

**Comment by YoheiKakiuchi** [comment]
Please test with these PR
https://github.com/euslisp/EusLisp/pull/292
https://github.com/jsk-ros-pkg/jsk_roseus/pull/568

**Comment by Affonso-Gui** [comment]
Was able to build and launch with the PR above. The remaining question is why does it work on 14.04 and not in 16.04? roseus version seems to be the same for both systems.
```
rosversion roseus
1.6.3
```

**Comment by Affonso-Gui** [comment]
Also, in `roseus.cpp` it appears that we already had an optional documentation parameter using `_defun` (https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/roseus/roseus.cpp#L1878-L1883)

Using `_defun` seemed more clear to me than using the `#undef - #define` schematics. Is this open to discussion?

@k-okada

**Comment by k-okada** [comment]
@Affonso-Gui I think it also fails on indigo

https://travis-ci.org/jsk-ros-pkg/jsk_roseus/builds/402501419

![indigo-fail](https://user-images.githubusercontent.com/493276/42627345-b7e03b1e-8607-11e8-8039-416d5f805055.png)

**Comment by Affonso-Gui** [comment]
Resuming:
- Segmentation fault is due to different `eus.h` versions between euslisp and roseus.
- Is solved by compiling roseus from source.

https://github.com/euslisp/EusLisp/pull/111

**Comment by Affonso-Gui** [comment]
Just for the record:
instructions to compile both roseus & euslisp from source can be found in https://github.com/jsk-ros-pkg/jsk_roseus#use-roseus-with-euslisp-built-from-source
