### ISSUE TITLE
debian_arm64:jessie travis fails

### ISSUE THREAD

**Issue by knorth55** [euslisp/EusLisp#370]
https://travis-ci.org/euslisp/EusLisp/jobs/513952717

Euslisp test fails because of this issue https://github.com/osrf/multiarch-docker-image-generation/issues/27 .

**Comment by k-okada** [comment]
It seems jessie was out of support list. https://discourse.ros.org/t/kinetic-builds-disabled-on-eol-platform-debian-jessie/5051
see https://github.com/euslisp/EusLisp/pull/376

**Comment by knorth55** [comment]
closed by #376
