### ISSUE TITLE
【質問】パッケージがバインドされたグローバル変数の存在の意味について。

### ISSUE THREAD

**Issue by Akioto** [euslisp/EusLisp#407]
jmanualの7.2 パッケージに於いて, パッケージシステムについての記述がありました, この疑問には段階がありますので順を追って書きます.

1.　パッケージの構造を知るためにdescribeで中身を見たいのだが、EUSLISPが提供する8つのパッケージのうち,GEOMETRY, COMPILER, XWINDOWについてはグローバル変数が割り当てられていない.

はじめはdescribe *package*のように変数を介して中身を見ていて、変数にバインドされていなければ中身を見れないと思っていたが, find-package "NAME"を使えば名前でパッケージ本体を呼び出せることがわかったため, 変数でバインドされていなくても問題なかった.

2．では, GOMETRY, COMPILER, XWINDOWにグローバル変数が割り当てられていないのはなぜか？

これについては1.4 開発履歴をみると1,991年にパッケージシステムがCommon Lispと互換になったとあることから, 上記の3パッケージはEusLisp特有で, Common Lisp由来のLispパッケージにのみグローバル変数が割当てられているのでは, という仮説に至りました.

3. では、なんのためにグローバル変数に割り当てているのか？

これはあくまで推測ですが, "find-package関数がCommon Lispでは存在しないため"。ではないでしょうか。シンボルの重複を防ぐための名前空間を提供するパッケージですから、本来名前で識別され、管理されるべきという意味では、find-packageを用いたインターフェースのほうが合理的に見えますし、実際に使用する場合はそちらで統一してしまえば良いと思うのでがどうなのでしょう？

**Comment by Affonso-Gui** [comment]
You are mainly answering your own question on item 2. The global package symbols were (probably) introduced to maintain compability with Common Lisp, and we had no reasons to delete them or to add symbols for the less used EusLisp packages.

Remember that the overall design of Lisp languages is *not* to avoid having duplicate forms for doing the same thing, but to allow to define more concise and meaningful vocabulary if someone finds useful to do so.

PS. Yes, `find-package` is defined in Common Lisp.
