### ISSUE TITLE
how to draw arrow-object temporally

### ISSUE THREAD

**Issue by HiroIshida** [euslisp/EusLisp#426]
I want to draw arrow-object temporally by using `draw-on` method. My attempt was the following
```lisp 
(require "models/arrow-object.l")
(make-irtviewer)
(setq *co* (arrow))
(send *co* :newcoords (make-coords :pos #f(100 100 100)))
(send *co* :draw-on :flush t)
```
but the obtained figure is like the below and it's same as visualization of normal coordinate. 
<img src="https://user-images.githubusercontent.com/38597814/80168506-ff159700-861d-11ea-8773-419a9e59d192.png" width="300">

I rather want to show arrow object like the below, which is obtained by `(objects *co*)` instead but it's not temporally.
<img src="https://user-images.githubusercontent.com/38597814/80168587-3126f900-861e-11ea-9bcf-27e352da3fba.png" width="300">

It would be grateful if someone tell me how to display the arrow-object temporally.

**Comment by k-okada** [comment]
`:draw-on` is the way to visualize (baseically) coordinates, for example
`(send *pr2* :larm :end-coords :draw-on :flush t)`
--
◉ Kei Okada



2020年4月24日(金) 11:31 Hirokazu Ishida <notifications@github.com>:

**Comment by Naoki-Hiraoka** [comment]
I think this code works.
```
(gl::draw-globjects (send *irtviewer* :viewer) (x::draw-things *co*) :draw-origin nil :clear nil)
```
