### ISSUE TITLE
string型をint型に変換したい

### ISSUE THREAD

**Issue by mqcmd196** [euslisp/EusLisp#455]
EusLispで例えば `"100"` をintの `100` に変換するにはどのようにしたらよいでしょうか (その逆は `string 100` のようにすればよい)．マニュアルやissueを読んでも見当たらなかったので質問させていただきました．

**Comment by knorth55** [comment]
`(read-from-string "10")`でどうでしょう？

**Comment by mqcmd196** [comment]
ありがとうございます．うまくいきました．
