### ISSUE TITLE
what is the best way to do funcall like thing with macro?

### ISSUE THREAD

**Issue by knorth55** [euslisp/EusLisp#459]
I want to do `funcall` or `apply` like thing with `macro` such as `cond`.
What is the best way to do it?
I do these thing with `eval`.

```lisp
(setq a 1)
(eval (append '(cond) '(((equal a 1) (print "hoge")) (t nil))))
;; "hoge"
```

**Comment by Affonso-Gui** [comment]
I cannot think of much besides writing another macro that would do the list operations and act like a funcall or apply. Of course this is only hiding the eval under the defmacro stuff, so I don't think there is anything wrong in going for the `eval` here.

A simplified version could be something like this:
```lisp
(defmacro macro-apply (fn arg-lst) (cons fn arg-lst))
(defmacro macro-funcall (fn &rest args) (cons fn args))

(setq a 1)
(macro-apply cond (((equal a 1) (print "hoge")) (t nil)))
;; "hoge"
```

**Comment by knorth55** [comment]
@Affonso-Gui thank you! I will use `eval`.
