### ISSUE TITLE
インストール後のフォントエラー

### ISSUE THREAD

**Issue by yuki-asano** [euslisp/EusLisp#97]
マシンをインストールしてから一回リブートしないと
以下のエラーが出ることがあります。
現状の対処法は、インストール後に一回リブートして、
DISPLAY= catkin build euslisp
とするようです。

leus@leus-ThinkPad-T410:~/ros/hydro_parent/build/euslisp$ make
can't load font "*-courier-medium-r-*-8-*"can't load font
"*-courier-medium-r-*-10-*"can't load font
"*-courier-medium-r-*-12-*"can't load font
"*-courier-medium-r-*-14-*"can't load font
"*-courier-medium-r-*-18-*"can't load font
"*-courier-bold-r-*-12-*"can't load font
"*-courier-bold-r-*-14-*"can't load font
"*-courier-bold-r-*-18-*"can't load font
"*-courier-bold-r-*-24-*"can't load font
"*-times-medium-r-*-10-*"can't load font
"*-times-medium-r-*-12-*"can't load font "*-times-bold-r-*-12-*"can't
load font "*-times-bold-r-*-14-*"can't load font
"*-times-bold-r-*-18-*"can't load font "*-times-bold-r-*-24-*"can't
load font "lucidasans-bold-12"can't load font
"lucidasans-bold-14"can't load font
"*-Helvetica-Bold-R-Normal-*-12-*"can't load font
"*-Helvetica-Medium-R-Normal-*-12-*"X Error of failed request:
BadFont (invalid Font parameter)
  Major opcode of failed request:  56 (X_ChangeGC)
  Resource id in failed request:  0x0
  Serial number of failed request:  49
  Current serial number in output stream:  58
make[4]: *** [/home/leus/ros/hydro_parent/src/euslisp/Linux64/obj/glconst.o]
エラー 1
[100%] Built target compile_euslisp

**Comment by k-okada** [comment]
solved via https://github.com/euslisp/EusLisp/pull/100
